In [19]:
import numpy as np
a1D = np.array([1, 2, 3, 4])
a2D = np.array([[1, 2], [3, 4]])
a3D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [1]:
#DIMENSION
import numpy as np
arr = np.array([[10,20, 30], [40, 50, 60]])  #2D numpy array
print(arr.ndim) #prints the dimension

2


In [4]:
#DIMENSION-3D
import numpy as np
arr = np.array([                   #3d numpy array
    [[10, 20, 30], [40, 50, 60]],  # First 2x3 matrix
    [[1, 2, 3], [4, 5, 6]]         # Second 2x3 matrix
])

print(arr.ndim)

3


In [5]:
#SIZE
import numpy as np
arr = np.array([[10,20, 30], [40, 50, 60]])  #2D numpy array
print(arr.size) # returns the total number of elements in the array

6


In [6]:
#SHAPE
import numpy as np
arr = np.array([[1, 2, 3, 4, 5, 6]])
print(arr.shape) #6 elements in a single dimension (a 1D vector).


(1, 6)


In [7]:
#SHAPE-2D
import numpy as np
arr = np.array([[10,20, 30], [40, 50, 60]])
print(arr.shape) #array’s dimensions ((2,3) → 2 rows, 3 columns).

(2, 3)


In [8]:
#RESHAPING ARRAY
import numpy as np

names = np.array(["Riya", "Dev", "Harshini", "Dev", "Tamanna", "Tanvi"]) #1D array
print("Original array:", names)
print("Original shape:", names.shape)

reshaped_names = names.reshape(2, 3) # Reshape into a 2D array with 2 rows and 3 columns
print("\nReshaped array:")
print(reshaped_names)
print("New shape:", reshaped_names.shape)

Original array: ['Riya' 'Dev' 'Harshini' 'Dev' 'Tamanna' 'Tanvi']
Original shape: (6,)

Reshaped array:
[['Riya' 'Dev' 'Harshini']
 ['Dev' 'Tamanna' 'Tanvi']]
New shape: (2, 3)


In [10]:
def pythonsum(n):
    a = range(n)          # Create a range object from 0 to n-1 for variable a (immutable sequence)
    b = range(n)          # Create another range object from 0 to n-1 for variable b
    c = []                # empty list to store results

    for i in range(n):    # Loop over numbers from 0 to n-1
        a[i] = i ** 2    
        b[i] = i ** 3     
        c.append(a[i] + b[i])  # Add the corresponding elements from a and b, append sum to c

    return c              # Return the list of sums

In [12]:
print(pythonsum(5)) #error cause range(n) creates an immutable sequence—it doesn’t allow changes to its elements.
#The line a[i] = i ** 2 tries to assign a new value to an element of range, which is invalid.


TypeError: 'range' object does not support item assignment

In [14]:
def pythonsum(n):
    a = [0] * n  # squares  #[0] * n creates a list of zeros you can update element-by-element.
    b = [0] * n  # cubes
    c = []       # results

    for i in range(n): 
        a[i] = i ** 2
        b[i] = i ** 3
        c.append(a[i] + b[i])

    return c

print(pythonsum(5))

[0, 2, 12, 36, 80]


In [16]:
import numpy as np
def numpysum(n)
  a = np.arange(n) ** 2  #Creates an array [0,1,..n-1] and element-wise sqauring
  b = np.arange(n) ** 3
  c = a + b              #element wise adding - NO LOOP Overhead, hence Memory Efficient
  return c

In [17]:
print(numpysum(15))

[   0    2   12   36   80  150  252  392  576  810 1100 1452 1872 2366
 2940]


In [21]:
import numpy as np
np.array([127, 128, 129], dtype=np.int8) #error np.int8 can only represent integers from -128 to 127.

#Values 128 and 129 overflow and wrap around:
#128 → -128
#129 → -127.

array([ 127, -128, -127], dtype=int8)

In [22]:
#Create int32 NumPy array
import numpy as np
np.array([127, 128, 129], dtype=np.int32) 

array([127, 128, 129], dtype=int32)

In [23]:
#ARRAY CREATION FUNCTIONS
import numpy as np
np.arange(10, 15, 0.1) # Values 10 to <15 with step 0.1

array([10. , 10.1, 10.2, 10.3, 10.4, 10.5, 10.6, 10.7, 10.8, 10.9, 11. ,
       11.1, 11.2, 11.3, 11.4, 11.5, 11.6, 11.7, 11.8, 11.9, 12. , 12.1,
       12.2, 12.3, 12.4, 12.5, 12.6, 12.7, 12.8, 12.9, 13. , 13.1, 13.2,
       13.3, 13.4, 13.5, 13.6, 13.7, 13.8, 13.9, 14. , 14.1, 14.2, 14.3,
       14.4, 14.5, 14.6, 14.7, 14.8, 14.9])

In [24]:
import numpy as np
np.arange(10) # Numbers 0 to 9

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
import numpy as np
np.arange(2, 10, dtype=float) # Numbers 2 to 9 as floats

array([2., 3., 4., 5., 6., 7., 8., 9.])

In [27]:
#LINSPACE- np.linspace(start, stop, num)
np.linspace(1., 2., 6)  # 6 evenly spaced numbers from 1 to 2


array([1. , 1.2, 1.4, 1.6, 1.8, 2. ])

In [28]:
# 3x3 identity matrix
import numpy as np
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
import numpy as np
np.eye(3, 5)  # 3x5 matrix with 1s on main diagonal

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [30]:
np.eye(3, 5, k=2)  # 3x5 matrix, 1s on diagonal shifted 2 columns right

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [31]:
np.eye(3, 5, k=-2)  # 3x5 matrix, 1s on diagonal shifted 2 rows down

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.]])

In [32]:
import numpy as np
np.diag([1, 2, 3])       # 3x3 matrix with 1,2,3 on main diagonal

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [33]:
import numpy as np
np.diag([1, 2, 3], 1)      # 4x4 matrix with 1,2,3 on diagonal above main (k=1)

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

In [34]:
a = np.array([[1, 2], [3, 4]])
np.diag(a)               # Extract main diagonal [1, 4] from 2x2 matrix a

array([1, 4])

In [35]:
#VANDERMONDE MATRIX
import numpy as np
np.vander(np.linspace(0, 2, 5), 2)  # Create Vandermonde matrix of degree 2

array([[0. , 1. ],
       [0.5, 1. ],
       [1. , 1. ],
       [1.5, 1. ],
       [2. , 1. ]])

In [36]:
np.vander([1, 2, 3, 4], 2)  # 4x2 Vandermonde matrix with columns [x^1, x^0]

array([[1, 1],
       [2, 1],
       [3, 1],
       [4, 1]])

In [37]:
np.vander((1, 2, 3, 4), 4)  # 4x4 Vandermonde matrix with powers 3 to 0

array([[ 1,  1,  1,  1],
       [ 8,  4,  2,  1],
       [27,  9,  3,  1],
       [64, 16,  4,  1]])

In [40]:
import numpy as np

x = [1, 2, 3]
N = 3

# Create Vandermonde matrix
# Each row is an element of x raised to decreasing powers from N-1 to 0
v = np.vander(x, N)

print(v)

[[1 1 1]
 [4 2 1]
 [9 3 1]]


In [41]:
np.vander(np.linspace(0, 2, 5), 2)
np.vander([1, 2, 3, 4], 2)  # N = 2 → 2 columns: x**1, x**0
np.vander([1, 2, 3, 4], 4)  # If N = 4 → 4 columns: x**3, x**2, x**1, x**0


array([[ 1,  1,  1,  1],
       [ 8,  4,  2,  1],
       [27,  9,  3,  1],
       [64, 16,  4,  1]])